name: organalytix
favicon: null
layout_spectrum: 0.08146677073091269
typography_spectrum: 0.8531719443853945
title: Org Analytix
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73759350-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#404140'
    - '#888580'
    - '#c40000'
    - '#47b3ea'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.8459020664449781
purpose: []
